### PR TITLE
Options parameter

### PR DESCRIPTION
**Pull request by mpotra**
+ Provides the optional `options` parameter to `.get()` methods.
Currently the only option available is `withCredentials` for XHR.

+ Provides support for `withCredentials` on XHR libraries, in order to allow browsers to pass cookies on.

Usage example: `vast.client.get(url, {'withCredentials': true}, cb)`

### CODE REVIEW

**Comment by hacfi** [comment]
:+1: Quite useful!

**Comment by oleynikd** [comment]
Hi,

So if use `vast.client.get(url, {'withCredentials': true}, cb)` browser should pass previously received cookies?

**Comment by mpotra** [comment]
@oleynikd Yes, it would include, in its request, any cookies set for a domain matching the `url` domain

**Comment by oleynikd** [comment]
Great! Thanks

**Pull request merged**
