### PR TITLE
Gitignore, and shinier "resolveURLTemplates"

### PR DESCRIPTION
**Pull request by shaqq**
Features:
- .gitignore file ignores node_modules and bower_components
- resolveURLTemplates is parameterized, so the macro values are not hard-coded like they are [here](https://github.com/dailymotion/vast-client-js/blob/master/src/util.coffee#L21)
- also adding another macro format, "%%MACRO_NAME%%", because urls may or may not come formatted
- added some test cases, all of which seem to pass

### CODE REVIEW

**Comment by flasheye** [comment]
Hi!
> maybe adding a templating function 

That would be a great Feature! 
I have to add [RANDOM] (uppercase) and [TIMESTAMP].

Is this possible? Thanks!

**Comment by michaelvial** [comment]
@flasheye I've done a PR https://github.com/dailymotion/vast-client-js/pull/140 for supporting theses missing macros. Can you tell me in the comments if this solution works for you?

**Comment by flasheye** [comment]
@michaelvial Thanks for the very quick update! :) 
Unfortunately, I do not use coffee script, i just include the finish .js file.
When i have time i will try coffee ;)

**Comment by michaelvial** [comment]
@flasheye Well, we've decided to merge it, theses macros are part of the spec (except for [RANDOM] but as we were handling [random] too, that wasn't a big change)
Anyway, we've released a new version (1.6.0) today that include the fix (in the bundle js file)

**Comment by flasheye** [comment]
@michaelvial THANKS so much - it works 👍 
keep up the good work!

**Pull request merged**
