### PR TITLE
rebase for upstream

### PR DESCRIPTION
**Pull request by realeyes-matthew**
### Description

This PR makes parsing of Ad Extensions recursive to support nested extension tags.

### Issue

Issue Link [Optional]

### Type
- [x] Breaking change
- [x] Enhancement
- [ ] Fix
- [ ] Documentation
- [ ] Tooling

### CODE REVIEW

**Comment by jgainfort** [comment]
@realeyes-matthew let's also get a PR prepped for @types/vast-client

**Comment by ZacharieTFR** [comment]
Hello @realeyes-matthew @jgainfort, 
Thanks for contributing ! 👍 
This feature is already supported in the [3.0-version](https://github.com/dailymotion/vast-client-js/tree/3.0-version) of vast-client. We will soon release it but you can already use it !

**Comment by jgainfort** [comment]
@ZacharieTFR  Cool. Is there a changelog between 2 and 3? Is there any documentation on migration from 2 -> 3 available? Thank you.

**Comment by ZacharieTFR** [comment]
The vast-client 3.0-version add support of VAST 4.1 (issue https://github.com/dailymotion/vast-client-js/issues/322 is missing in order to be fully 4.1 compliant).
You can find migration doc here: https://github.com/dailymotion/vast-client-js/blob/3.0-migration/docs/api/3.0-migration.md. 
When we release version 3.0, we will add more documentation about it 😅

**Comment by ZacharieTFR** [comment]
Hello,

Version 3.0 is officially released ! 🎉 Please find the release note here https://github.com/dailymotion/vast-client-js/releases/tag/3.0.0

**Pull request closed without merging**
